/**
 * Interactive setup wizard for the XYON Reddit Radar.
 *
 * Run with:  npm run setup
 *
 * Prompts for the few credentials the Radar needs and writes them to .env.
 * Existing values are shown as defaults so re-running is safe.
 */

import { readFile, writeFile, access } from 'fs/promises';
import { createInterface } from 'readline/promises';
import { stdin, stdout } from 'process';

const ENV_PATH = new URL('./.env', import.meta.url);

async function fileExists(url) {
  try { await access(url); return true; } catch { return false; }
}

/** Parse a simple KEY=value .env into a map. */
function parseEnv(text) {
  const map = {};
  for (const line of text.split('\n')) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/);
    if (m) map[m[1]] = m[2];
  }
  return map;
}

console.log(`
╭───────────────────────────────────────────────╮
│   XYON Reddit Radar — setup                     │
╰───────────────────────────────────────────────╯

You'll need a Reddit "script" app (read-only). If you don't have one yet:
  1. Go to  https://www.reddit.com/prefs/apps   (logged into your account)
  2. "create another app…" → type: script → redirect uri: http://localhost:8080
  3. client ID = the string just under the app name
     secret    = the field labelled "secret"

The Anthropic key (for AI draft replies) is optional — leave blank to skip.
Press Enter to keep an existing value shown in [brackets].
`);

// Start from .env if present, else .env.example as a template.
let base = {};
if (await fileExists(ENV_PATH)) {
  base = parseEnv(await readFile(ENV_PATH, 'utf8'));
} else if (await fileExists(new URL('./.env.example', import.meta.url))) {
  base = parseEnv(await readFile(new URL('./.env.example', import.meta.url), 'utf8'));
  // Clear the example placeholders so they don't look like real values.
  for (const k of Object.keys(base)) {
    if (/your_|XXXX|here|username/i.test(base[k])) base[k] = '';
  }
}

// Create the prompt interface only now — after all file I/O — so piped/non-TTY
// input doesn't reach EOF and auto-close the interface mid-setup.
const rl = createInterface({ input: stdin, output: stdout });
async function ask(prompt, current) {
  const suffix = current ? ` [${current.length > 8 ? current.slice(0, 4) + '…' : current}]` : '';
  const answer = (await rl.question(`${prompt}${suffix}: `)).trim();
  return answer || current || '';
}

const clientId = await ask('Reddit client ID', base.REDDIT_SCAN_CLIENT_ID);
const secret   = await ask('Reddit secret', base.REDDIT_SCAN_SECRET);
let username   = await ask('Your Reddit username (for the user-agent)',
  (base.REDDIT_USER_AGENT || '').replace(/^.*by u\//, ''));
username = username.replace(/^u\//, '');
const anthropic = await ask('Anthropic API key (optional, Enter to skip)', base.ANTHROPIC_API_KEY);

await rl.close();

base.REDDIT_SCAN_CLIENT_ID = clientId;
base.REDDIT_SCAN_SECRET = secret;
base.REDDIT_USER_AGENT = `xyon-listener/1.0 by u/${username || 'anonymous'}`;
base.ANTHROPIC_API_KEY = anthropic;
base.PORT = base.PORT || '3000';

// Preserve any other keys already present (Meta/TikTok/etc.), write KEY=value lines.
const lines = ['# Generated by `npm run setup` — do not commit this file.'];
for (const [k, v] of Object.entries(base)) lines.push(`${k}=${v}`);
await writeFile(ENV_PATH, lines.join('\n') + '\n');

const haveReddit = clientId && secret;
console.log(`
✓ Wrote .env

  Reddit scanning : ${haveReddit ? 'ready' : 'MISSING client ID / secret — re-run setup'}
  AI drafts       : ${anthropic ? 'enabled' : 'disabled (no Anthropic key — scanning still works)'}

Next:  npm start   →   open  http://localhost:3000/reddit   →   click "Scan now"
`);
